version: '3.7'

services:
  ngrok:
    image: ngrok/ngrok:latest
    container_name: commonplace-ngrok
    network_mode: "host"
    # restart: unless-stopped
    command:
      - "start"
      - "--all"
      - "--log=stdout"
      - "--config"
      - "/etc/ngrok.yml"
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    ports:
      - 4040:4040
    depends_on:
      - commonplace-site
  commonplace-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: commonplace-server-image
    volumes:
      - ./server/:/usr/src/app
      - image-store:/usr/src/app/image-store
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - NODE_ENV=production
    networks:
      - app-network
  mongo:
    image: mongo:7.0
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network
  commonplace-site:
    build:
      context: ./site
      dockerfile: Dockerfile
    image: commonplace-site-image
    volumes:
      - ./client/:/usr/app
      - /usr/app/node_modules
    depends_on:
      - commonplace-server
    ports:
      - "8080:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  image-store:
  mongo-data:
  node_modules:
  web-root:
    driver: local
    